import { Header, Footer } from "@/components";
import { DarkModeProvider } from "./../context/DarkModeContext";
import "./globals.css";
import { Poppins, DM_Sans } from "next/font/google";

export const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

export const dmSans = DM_Sans({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

const metadata = {
	title: "My portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<DarkModeProvider>
			<html lang="en" className="scroll-smooth">
				<body className={`${poppins.className} dark:bg-bgDark bg-white `}>
					<Header></Header>
					{children}
					<Footer id={"contact"}></Footer>
				</body>
			</html>
		</DarkModeProvider>
	);
}
