export * from './BuildingIcon';
export * from './CalendarIcon';
export * from './GitIcon';
export * from './InstagramIcon';
export * from './LinkedInIcon';
export * from './LinkIcon';
export * from './LocationIcon';
export * from './LogoIcon';
export * from './TelegramIcon';
